version: '3.7'

services:
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  vbuilder:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    volumes:
      - ./:/app
    container_name: vehicle_builder
    working_dir: /app
    command: "python3 main.py"
    tty: true
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - postgres